baseurl: https://perry.alexander.name/hnrs190/
title: HNRS 190
subtitle: Freshman Honors Symposium
when: 4:00-4:45 T
ohrs: 1:30-2:30 TR
where: 108 Nunemaker Center
markdown: kramdown
name: HNRS 190
description: HNRS 190 - A Just Machine at The Univ of Kansas
url: https://perry.alexander.name/hnrs190
